Repository Learning-Python-Team/Chess, pull requests merged in 2019-08, with the labels that each got.

#5 Added/fixed some stuff
  chess.py
Labels: documentation

#13 Fixed Board.draw()
  chess.py
Labels: bug

#14 Fix Board.move error and a whole lot more
  chess.py
  chess_pieces.py
Labels: bug, enhancement

#15 Added logging
  chess.py
Labels: documentation, enhancement

#18 Minor change
  chess_pieces.py
Labels: enhancement

#21 Implemented valid move checking
  chess.py
  chess_pieces.py
Labels: documentation, enhancement
